[2024-08-03 11:04:44,523] INFO: HTTP Request: POST https://api.telegram.org/bot7451346969:AAGRBFxAbGpTwZbV77leIJs3PJtFyP3tK1M/setWebhook "HTTP/1.1 200 OK"
[2024-08-03 11:04:44,554] INFO: Running on http://127.0.0.1:8443 (CTRL + C to quit)
[2024-08-03 11:16:14,763] INFO: HTTP Request: POST https://api.telegram.org/bot7451346969:AAGRBFxAbGpTwZbV77leIJs3PJtFyP3tK1M/setWebhook "HTTP/1.1 200 OK"
[2024-08-03 11:16:14,766] INFO: Running on http://0.0.0.0:8443 (CTRL + C to quit)
[2024-08-03 11:16:40,626] INFO: HTTP Request: POST https://api.telegram.org/bot7451346969:AAGRBFxAbGpTwZbV77leIJs3PJtFyP3tK1M/setWebhook "HTTP/1.1 200 OK"
[2024-08-03 11:16:40,630] INFO: Running on http://0.0.0.0:8443 (CTRL + C to quit)
[2024-08-03 11:27:51,320] INFO: HTTP Request: POST https://api.telegram.org/bot7451346969:AAGRBFxAbGpTwZbV77leIJs3PJtFyP3tK1M/setWebhook "HTTP/1.1 200 OK"
[2024-08-03 11:27:51,354] INFO: Running on http://127.0.0.1:8443 (CTRL + C to quit)
[2024-08-04 11:28:01,962] INFO in _client at line 1729: HTTP Request: POST https://api.telegram.org/bot7451346969:AAGRBFxAbGpTwZbV77leIJs3PJtFyP3tK1M/setWebhook "HTTP/1.1 200 OK"
[2024-08-04 11:28:01,995] INFO in logging at line 106: Running on http://127.0.0.1:8443 (CTRL + C to quit)
[2024-08-05 20:25:24,032] ERROR in logs at line 35: This is a test error
NoneType: None
[2024-08-05 20:25:36,855] INFO in _client at line 1013: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
[2024-08-05 20:25:37,461] INFO in _client at line 1729: HTTP Request: POST https://api.telegram.org/bot7451346969:AAGRBFxAbGpTwZbV77leIJs3PJtFyP3tK1M/setWebhook "HTTP/1.1 200 OK"
[2024-08-05 20:25:37,493] INFO in logging at line 106: Running on http://127.0.0.1:8443 (CTRL + C to quit)
[2024-08-05 20:39:17,257] ERROR in logs at line 35: This is a test error
NoneType: None
[2024-08-05 20:39:29,206] INFO in _client at line 1013: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
[2024-08-05 20:39:43,468] INFO in _client at line 1013: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
[2024-08-05 20:39:43,939] INFO in _client at line 1729: HTTP Request: POST https://api.telegram.org/bot7451346969:AAGRBFxAbGpTwZbV77leIJs3PJtFyP3tK1M/setWebhook "HTTP/1.1 200 OK"
[2024-08-05 20:39:43,970] INFO in logging at line 106: Running on http://127.0.0.1:8443 (CTRL + C to quit)
[2024-08-05 20:40:21,267] ERROR in logs at line 35: This is a test error
NoneType: None
[2024-08-05 20:40:29,406] INFO in _client at line 1013: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
[2024-08-07 09:46:14,112] ERROR in logs at line 35: This is a test error
NoneType: None
[2024-08-07 09:46:22,016] INFO in _client at line 1013: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
[2024-08-07 10:03:52,264] INFO in _client at line 1013: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
[2024-08-07 10:03:52,375] ERROR in logs at line 43: An unexpected error occurred while loading the rave model
Traceback (most recent call last):
  File "/home/runner/Rave/main.py", line 31, in <module>
    rave_model = Rave.load_from_file("data/events.json")
AttributeError: type object 'Rave' has no attribute 'load_from_file'. Did you mean: 'load_from_db'?
[2024-08-07 10:03:52,376] ERROR in logs at line 43: Failed to initialize rave_model. Handlers not set up.
NoneType: None
[2024-08-07 10:03:52,789] INFO in _client at line 1729: HTTP Request: POST https://api.telegram.org/bot7451346969:AAGRBFxAbGpTwZbV77leIJs3PJtFyP3tK1M/setWebhook "HTTP/1.1 200 OK"
[2024-08-07 10:03:52,826] INFO in logging at line 106: Running on http://0.0.0.0:8443 (CTRL + C to quit)
[2024-08-07 10:08:57,576] INFO in _client at line 1013: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
[2024-08-07 10:16:02,954] ERROR in logs at line 35: This is a test error
NoneType: None
[2024-08-07 10:16:13,311] INFO in _client at line 1013: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
[2024-08-07 10:16:13,814] INFO in _client at line 1729: HTTP Request: POST https://api.telegram.org/bot7451346969:AAGRBFxAbGpTwZbV77leIJs3PJtFyP3tK1M/setWebhook "HTTP/1.1 200 OK"
[2024-08-07 10:16:13,851] INFO in logging at line 106: Running on http://0.0.0.0:8443 (CTRL + C to quit)
[2024-08-07 10:25:18,979] ERROR in logs at line 35: This is a test error
NoneType: None
[2024-08-07 10:25:25,098] ERROR in logs at line 35: This is a test error
NoneType: None
[2024-08-07 10:25:38,867] INFO in _client at line 1013: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
[2024-08-07 10:25:39,391] INFO in _client at line 1729: HTTP Request: POST https://api.telegram.org/bot7451346969:AAGRBFxAbGpTwZbV77leIJs3PJtFyP3tK1M/setWebhook "HTTP/1.1 200 OK"
[2024-08-07 10:25:39,431] INFO in logging at line 106: Running on http://0.0.0.0:8443 (CTRL + C to quit)
[2024-08-07 10:32:03,440] ERROR in logs at line 35: This is a test error
NoneType: None
[2024-08-07 10:32:12,345] INFO in _client at line 1013: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
[2024-08-07 10:32:12,907] INFO in _client at line 1729: HTTP Request: POST https://api.telegram.org/bot7451346969:AAGRBFxAbGpTwZbV77leIJs3PJtFyP3tK1M/setWebhook "HTTP/1.1 200 OK"
[2024-08-07 10:32:12,971] INFO in logging at line 106: Running on http://0.0.0.0:8443 (CTRL + C to quit)
[2024-08-07 10:37:54,245] INFO in _client at line 1013: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
[2024-08-07 10:37:54,784] INFO in _client at line 1729: HTTP Request: POST https://api.telegram.org/bot7451346969:AAGRBFxAbGpTwZbV77leIJs3PJtFyP3tK1M/setWebhook "HTTP/1.1 200 OK"
[2024-08-07 10:37:54,831] INFO in logging at line 106: Running on http://0.0.0.0:8443 (CTRL + C to quit)
